platform :ios, '7.0'
use_frameworks!

source 'https://github.com/ajayempty/ios_specFile.git'

target 'ios_specFile_Example' do
  pod 'ios_specFile', :path => '~/Documents/Classes/ios_specFile'
end
target 'ios_specFile_Tests' do
end
